#!/bin/bash
# AOTA.EXE - Startup Script for Raspberry Pi
# Usage: ./start.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

PORT=8080

# --- .env 読み込み ---
if [ ! -f .env ]; then
  echo "[ERROR] .env ファイルが見つかりません"
  echo "  cp .env.example .env して GEMINI_API_KEY を設定してください"
  exit 1
fi

source .env

if [ -z "$GEMINI_API_KEY" ] || [ "$GEMINI_API_KEY" = "your-api-key-here" ]; then
  echo "[ERROR] .env の GEMINI_API_KEY を設定してください"
  exit 1
fi

# --- config.js 生成 ---
cat > config.js << CONFIGEOF
// AOTA.EXE - Configuration (auto-generated by start.sh)
const CONFIG = {
  GEMINI_API_KEY: '${GEMINI_API_KEY}',
  GEMINI_TEXT_MODEL: 'gemini-2.0-flash',
  GEMINI_IMAGE_MODEL: 'gemini-2.5-flash-preview-05-20',
  GEMINI_API_BASE: 'https://generativelanguage.googleapis.com/v1beta/models',
  EXHIBITION_START: '2025-03-06',
  EXHIBITION_END: '2025-03-08',
  EXHIBITION_HOURS: { start: 12, end: 19 },
  MAX_INPUT_LENGTH: 60,
  BATTLE_INTERVAL_MS: 60 * 60 * 1000,
  BATTLE_STARTUP_DELAY_MS: 20 * 1000,
  IMAGE_GENERATION_INTERVAL: 5,
  REFERENCE_IMAGE_PATH: 'img/reference.jpg',
};
CONFIGEOF

echo "[OK] config.js 生成完了"

# --- 既存サーバーを停止 ---
pkill -f "python3 -m http.server $PORT" 2>/dev/null || true
sleep 0.5

# --- HTTPサーバー起動 ---
echo "[OK] HTTP サーバー起動 (port $PORT)..."
python3 -m http.server $PORT --directory "$SCRIPT_DIR" &
SERVER_PID=$!
sleep 1

# --- ブラウザ起動（キオスクモード） ---
URL="http://localhost:$PORT/index.html"
echo "[OK] ブラウザ起動: $URL"

if command -v chromium-browser &>/dev/null; then
  chromium-browser --kiosk --noerrdialogs --disable-infobars --incognito "$URL" &
elif command -v chromium &>/dev/null; then
  chromium --kiosk --noerrdialogs --disable-infobars --incognito "$URL" &
elif command -v firefox &>/dev/null; then
  firefox --kiosk "$URL" &
else
  echo "[INFO] ブラウザを手動で開いてください: $URL"
fi

echo ""
echo "========================================="
echo "  AOTA.EXE 起動完了!"
echo "  URL: $URL"
echo "  停止: Ctrl+C"
echo "========================================="

# Ctrl+C で停止
trap "kill $SERVER_PID 2>/dev/null; echo '[STOPPED]'; exit 0" INT TERM
wait $SERVER_PID
